#!/usr/bin/env tsx
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as crypto from 'node:crypto';
import { execSync } from 'node:child_process';

function sha256(content: string): string {
  return crypto.createHash('sha256').update(content, 'utf8').digest('hex');
}

function usage() {
  console.log(`Usage: npx tsx scripts/init.ts --dest /path/to/vault [--profile org-operations] [--name "My Vault"]

Creates a new DocWright vault with the full directory structure,
config files, and pre-commit hooks.

Options:
  --dest              Path to the new vault directory (required)
  --profile           Profile to use (default: org-operations)
  --name              Vault display name (default: basename of --dest)
  --docwright-path    Path to DocWright installation (default: inferred from script location)
  --help              Show this help
`);
}

function inferDocWrightPath(): string | null {
  const scriptDir = path.dirname(new URL(import.meta.url).pathname);
  const candidate = path.resolve(scriptDir, '..');
  if (fs.existsSync(path.join(candidate, 'scripts', 'init.ts')) ||
      fs.existsSync(path.join(candidate, 'dist', 'mcp', 'server.js'))) {
    return candidate;
  }
  return null;
}

function main() {
  const args = process.argv.slice(2);
  if (args.includes('--help') || args.includes('-h')) { usage(); process.exit(0); }

  let dest = '';
  let profile = 'org-operations';
  let vaultName = '';
  let docwrightPath = process.env.DOCWRIGHT_PATH || inferDocWrightPath() || '';

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--dest') dest = path.resolve(args[++i]);
    else if (args[i] === '--profile') profile = args[++i];
    else if (args[i] === '--name') vaultName = args[++i];
    else if (args[i] === '--docwright-path') docwrightPath = path.resolve(args[++i]);
    else { console.error(`Unknown option: ${args[i]}`); usage(); process.exit(1); }
  }

  if (!dest) { console.error('Error: --dest is required'); usage(); process.exit(1); }

  if (fs.existsSync(dest)) {
    const entries = fs.readdirSync(dest).filter(e => !e.startsWith('.'));
    if (entries.length > 0) {
      console.error(`Error: destination ${dest} exists and is not empty`);
      process.exit(1);
    }
  } else {
    fs.mkdirSync(dest, { recursive: true });
  }

  if (!vaultName) vaultName = path.basename(dest);

  if (!docwrightPath || !fs.existsSync(path.join(docwrightPath, 'dist', 'mcp', 'server.js'))) {
    console.error('Warning: DOCWRIGHT_PATH not set and dist/mcp/server.js not found.');
    console.error('  Set DOCWRIGHT_PATH or pass --docwright-path so .mcp.json works.');
    console.error('  Continuing with placeholder — edit .env after init.\n');
  }

  const dirs = ['proposals', 'plans', 'docs', '.docwright', 'policies'];
  for (const d of dirs) {
    fs.mkdirSync(path.join(dest, d), { recursive: true });
  }

  // .env
  const envPath = path.join(dest, '.env');
  if (!fs.existsSync(envPath)) {
    fs.writeFileSync(envPath, [
      '# DocWright Vault — generated by docwright init',
      '# Machine identity is always $(hostname) — never set it here.',
      `OPCODE_USER_NAME=""`,
      `OPCODE_USER_EMAIL=""`,
      '',
      '# Path to the DocWright tool installation',
      `DOCWRIGHT_PATH="${docwrightPath}"`,
      '',
      '# This vault\'s root',
      `DOCWRIGHT_VAULT_ROOT="${dest}"`,
      '',
    ].join('\n'), 'utf8');
    console.log('  ✓ .env');
  }

  // .mcp.json
  const mcpPath = path.join(dest, '.mcp.json');
  if (!fs.existsSync(mcpPath)) {
    const mcpContent = {
      mcpServers: {
        'dw-vault': {
          type: 'stdio',
          command: 'node',
          args: ['${DOCWRIGHT_PATH}/dist/mcp/server.js', '--mode', 'vault'],
          env: {
            DOCWRIGHT_PATH: '${DOCWRIGHT_PATH}',
            DOCWRIGHT_VAULT_ROOT: '${DOCWRIGHT_VAULT_ROOT}',
          },
        },
        'dw-upstream': {
          type: 'stdio',
          command: 'node',
          args: ['${DOCWRIGHT_PATH}/dist/mcp/server.js', '--mode', 'upstream'],
          env: {
            DOCWRIGHT_PATH: '${DOCWRIGHT_PATH}',
          },
        },
      },
    };
    fs.writeFileSync(mcpPath, JSON.stringify(mcpContent, null, 2) + '\n', 'utf8');
    console.log('  ✓ .mcp.json (dw-vault + dw-upstream)');
  }

  // profile.json (vault-root override stub)
  const profilePath = path.join(dest, 'profile.json');
  if (!fs.existsSync(profilePath)) {
    fs.writeFileSync(profilePath, JSON.stringify({
      docwrightProfileVersion: '1',
      name: vaultName,
      displayName: vaultName,
      description: `DocWright vault created by docwright init`,
      profile: profile,
      extends: `src/profiles/${profile}/profile.json`,
      documentTypes: [],
      requiredFrontmatter: [],
      optionalFrontmatter: [],
      features: {},
    }, null, 2) + '\n', 'utf8');
    console.log('  ✓ profile.json (vault-root override)');
  }

  // brand.json
  const brandPath = path.join(dest, 'brand.json');
  if (!fs.existsSync(brandPath)) {
    fs.writeFileSync(brandPath, JSON.stringify({
      name: vaultName,
      logoPath: '',
    }, null, 2) + '\n', 'utf8');
    console.log('  ✓ brand.json');
  }

  // .docwright/config.json
  const configPath = path.join(dest, '.docwright', 'config.json');
  const pkgPath = path.join(docwrightPath, 'package.json');
  let adoptVersion = '0.0.0';
  try { adoptVersion = JSON.parse(fs.readFileSync(pkgPath, 'utf8')).version ?? '0.0.0'; } catch { /* ignore */ }
  const adoptDate = new Date().toISOString().split('T')[0];
  if (!fs.existsSync(configPath)) {
    fs.writeFileSync(configPath, JSON.stringify({
      schema_version: '1',
      adopt_version: adoptVersion,
      adopt_date: adoptDate,
      adopt_mode: 'init',
    }, null, 2) + '\n', 'utf8');
    console.log('  ✓ .docwright/config.json (schema_version: 1, adopt_version: ' + adoptVersion + ')');
  }

  // .docwright/.gitignore
  const giPath = path.join(dest, '.docwright', '.gitignore');
  if (!fs.existsSync(giPath)) {
    fs.writeFileSync(giPath, '*\n!registry.example.json\n!manifest.json\n', 'utf8');
    console.log('  ✓ .docwright/.gitignore');
  }

  // .docwright/registry.json
  const regPath = path.join(dest, '.docwright', 'registry.json');
  if (!fs.existsSync(regPath)) {
    fs.writeFileSync(regPath, JSON.stringify({ projects: [] }, null, 2) + '\n', 'utf8');
    console.log('  ✓ .docwright/registry.json');
  }

  // .docwright/registry.example.json
  const regExPath = path.join(dest, '.docwright', 'registry.example.json');
  if (!fs.existsSync(regExPath)) {
    fs.writeFileSync(regExPath, JSON.stringify({
      projects: [
        {
          name: 'Example Project',
          path: '../example-infra',
          profile: 'infra-topology',
          last_session: 'docs/session-notes/session_note_yyyymmdd.md',
        },
      ],
    }, null, 2) + '\n', 'utf8');
    console.log('  ✓ .docwright/registry.example.json');
  }

  // docs/friction-log.md
  const frictionPath = path.join(dest, 'docs', 'friction-log.md');
  if (!fs.existsSync(frictionPath)) {
    fs.writeFileSync(frictionPath, [
      '# Friction Log',
      '',
      'Track UX friction, bugs, and feature requests encountered while using DocWright.',
      '',
      '## Format',
      '',
      '| Date | Category | Description | Upstream Issue |',
      '|------|----------|-------------|----------------|',
      '|      |          |             |                |',
      '',
      '',

      '---',
      'Categories: bug | feature-request | ux-friction | docs-gap | missing-abstraction',
    ].join('\n'), 'utf8');
    console.log('  ✓ docs/friction-log.md');
  }

  // proposals/.gitkeep
  fs.writeFileSync(path.join(dest, 'proposals', '.gitkeep'), '', 'utf8');
  fs.writeFileSync(path.join(dest, 'plans', '.gitkeep'), '', 'utf8');
  fs.writeFileSync(path.join(dest, 'docs', '.gitkeep'), '', 'utf8');
  console.log('  ✓ directory structure (proposals/, plans/, docs/)');

  // Seed pilot policy atoms from DocWright installation
  const atomIds = ['commit-format', 'frontmatter-validate', 'no-work-before-approval'];
  const atomSeedFiles = ['atom.yaml', 'context.md', 'check.ts', 'check.js'];
  let atomsSeeded = 0;
  for (const atomId of atomIds) {
    const srcDir = path.join(docwrightPath, 'policies', atomId);
    const dstDir = path.join(dest, 'policies', atomId);
    if (!fs.existsSync(srcDir)) continue;
    fs.mkdirSync(dstDir, { recursive: true });
    for (const f of atomSeedFiles) {
      const src = path.join(srcDir, f);
      if (fs.existsSync(src)) {
        fs.copyFileSync(src, path.join(dstDir, f));
        atomsSeeded++;
      }
    }
  }
  if (atomsSeeded > 0) console.log(`  ✓ policies/ (${atomIds.length} pilot atoms seeded)`);

  // .docwright/manifest.json — records every file written by init for adopt --upgrade
  const manifestPath = path.join(dest, '.docwright', 'manifest.json');
  const managedFiles = [
    '.env', '.mcp.json', 'profile.json', 'brand.json',
    '.docwright/config.json', '.docwright/.gitignore',
    '.docwright/registry.json', '.docwright/registry.example.json',
    'docs/friction-log.md',
  ];
  const manifest: Record<string, string> = {};
  for (const rel of managedFiles) {
    const abs = path.join(dest, rel);
    if (fs.existsSync(abs)) {
      manifest[rel] = sha256(fs.readFileSync(abs, 'utf8'));
    }
  }
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  console.log('  ✓ .docwright/manifest.json (' + Object.keys(manifest).length + ' managed files)');

  console.log(`\n✅ DocWright vault initialized at ${dest}`);
  console.log(`\nNext steps:`);
  console.log(`  1. git init ${dest}`);
  console.log(`  2. Edit ${path.join(dest, '.env')} — set your identity`);
  console.log(`  3. npm run hook:install -- --vault "${dest}"`);
  console.log(`  4. Open ${dest} in the DocWright Web UI`);
  console.log(`  5. Create your first proposal`);
}

main();
