#!/bin/bash
# =============================================================================
# DocWright - Hook Installer
# =============================================================================
# Syncs tracked pre-commit source to .git/hooks/ and validates installation.
# Run after cloning, or when scripts/pre-commit.sh is updated.
#
# Usage:
#   npm run hook:install                    # Install hooks for this repo
#   npm run hook:install -- --vault /path   # Install hooks in a vault repo
#
# Supports DOCWRIGHT_PATH env var for vault installations.
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
fail() { echo -e "${RED}[✗]${NC} $1"; exit 1; }
pass() { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }

# Parse args
VAULT_TARGET=""
DOCWRIGHT_PATH="${DOCWRIGHT_PATH:-}"

while [ $# -gt 0 ]; do
  case "$1" in
    --vault)
      shift
      VAULT_TARGET="$1"
      ;;
    --docwright-path)
      shift
      DOCWRIGHT_PATH="$1"
      ;;
    *)
      fail "Unknown option: $1"
      ;;
  esac
  shift
done

# Determine paths
if [ -n "$VAULT_TARGET" ]; then
  # Vault installation — install hooks in the vault repo
  REPO_ROOT="$(cd "$VAULT_TARGET" && pwd)"
  [ -d "$REPO_ROOT/.git" ] || fail "Not a git repository: $REPO_ROOT"

  # DOCWRIGHT_PATH must point to the DocWright tool repo
  if [ -z "$DOCWRIGHT_PATH" ]; then
    # Try to resolve relative to this script
    SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
    if [ -f "$SCRIPT_DIR/scripts/pre-commit.sh" ]; then
      DOCWRIGHT_PATH="$SCRIPT_DIR"
    else
      fail "DOCWRIGHT_PATH is required for vault installations. Set DOCWRIGHT_PATH or use --docwright-path"
    fi
  fi
  DOCWRIGHT_PATH="$(cd "$DOCWRIGHT_PATH" && pwd)"
  [ -f "$DOCWRIGHT_PATH/scripts/pre-commit.sh" ] || fail "DocWright not found at $DOCWRIGHT_PATH (missing scripts/pre-commit.sh)"

  SOURCE_HOOK="$DOCWRIGHT_PATH/scripts/pre-commit.sh"
  echo "Installing DocWright hooks in vault: $REPO_ROOT"
  echo "  DocWright path: $DOCWRIGHT_PATH"
else
  # Self installation — install hooks in the DocWright repo itself
  REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
  SOURCE_HOOK="$REPO_ROOT/scripts/pre-commit.sh"
  DOCWRIGHT_PATH="$REPO_ROOT"
  echo "DocWright Hook Installer (self)"
fi

cd "$REPO_ROOT" || exit 1
echo "========================="
echo ""

# Check source exists
[ ! -f "$SOURCE_HOOK" ] && fail "Source hook not found at $SOURCE_HOOK"

# Ensure .git/hooks exists
mkdir -p .git/hooks

# Copy with validation
cp "$SOURCE_HOOK" .git/hooks/pre-commit && chmod +x .git/hooks/pre-commit
pass "Copied hook -> .git/hooks/pre-commit"

# For vault installations, write a .env if not present
if [ -n "$VAULT_TARGET" ] && [ ! -f "$REPO_ROOT/.env" ]; then
  cat > "$REPO_ROOT/.env" <<-ENVEOF
# DocWright Vault — environment (generated by hook:install)
# Machine identity is always \$(hostname) — never set it here.
OPCODE_USER_NAME=""
OPCODE_USER_EMAIL=""

# Path to the DocWright tool installation
DOCWRIGHT_PATH="$DOCWRIGHT_PATH"

# This vault's root (auto-detected)
DOCWRIGHT_VAULT_ROOT="$REPO_ROOT"
ENVEOF
  pass "Created .env with DOCWRIGHT_PATH=$DOCWRIGHT_PATH"
fi

# Also write .mcp.json if vault and not present
if [ -n "$VAULT_TARGET" ] && [ ! -f "$REPO_ROOT/.mcp.json" ]; then
  cat > "$REPO_ROOT/.mcp.json" <<-MCPEOF
{
  "mcpServers": {
    "dw-vault": {
      "type": "stdio",
      "command": "node",
      "args": ["\${DOCWRIGHT_PATH}/dist/mcp/server.js", "--mode", "vault"],
      "env": {
        "DOCWRIGHT_PATH": "\${DOCWRIGHT_PATH}",
        "DOCWRIGHT_VAULT_ROOT": "\${DOCWRIGHT_VAULT_ROOT}"
      }
    },
    "dw-upstream": {
      "type": "stdio",
      "command": "node",
      "args": ["\${DOCWRIGHT_PATH}/dist/mcp/server.js", "--mode", "upstream"],
      "env": {
        "DOCWRIGHT_PATH": "\${DOCWRIGHT_PATH}"
      }
    }
  }
}
MCPEOF
  pass "Created .mcp.json with dw-vault + dw-upstream"
fi

# Verify match (self-install only)
if [ -z "$VAULT_TARGET" ]; then
  if diff -q "$SOURCE_HOOK" .git/hooks/pre-commit > /dev/null 2>&1; then
    pass "Integrity verified: source and installed hook match"
  else
    fail "Integrity FAILED: files differ after copy"
  fi
fi

# Test hook is executable
[ -x ".git/hooks/pre-commit" ] && pass "Hook is executable" || fail "Hook not executable"

# Quick smoke test
echo ""
echo "Running smoke test..."
if bash .git/hooks/pre-commit > /dev/null 2>&1; then
    pass "Smoke test: pre-commit runs cleanly"
else
    warn "Smoke test: pre-commit found issues (expected on dirty tree)"
fi

echo ""
pass "Hooks installed successfully"
